"""empty message

Revision ID: f9506fc4cf81
Revises: None
Create Date: 2016-07-20 20:29:46.691158

"""

# revision identifiers, used by Alembic.
revision = 'f9506fc4cf81'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
